# Created by https://github.com/eth0izzle/security-skills/
name: Sensor Update Enforcer - Scheduled
description: Runs every 4 hours. Tracks sensor release standings in a collection, sleeps 10 minutes, then enforces grace periods by moving stale hosts to a force-update group and cleaning up hosts that have updated.
parameters: {}
provision_on_install: true
trigger:
    next:
        - UpdateSensorTracker
    event: Schedule
    name: Sensor Update Enforcer - Scheduled
    schedule:
        time_cycle: 0 0/4 * * *
        start_date: ""
        end_date: ""
        tz: America/Los_Angeles
        skip_concurrent: true
actions:
    UpdateSensorTracker:
        id: functions.update-sensor-tracker.update-sensor-tracker
        name: update-sensor-tracker
        next:
            - Sleep
        properties:
            platforms:
                - windows
                - mac
                - linux
    Sleep:
        id: 4f1af1ae4c13dc1e3bcd725f8dc0f63b
        default_name: Sleep
        name: Sleep
        next:
            - EnforceGracePeriod
        properties:
            sleep_time: 10m
        version_constraint: ~1
    EnforceGracePeriod:
        id: functions.enforce-grace-period.enforce-grace-period
        name: enforce-grace-period
        properties: {}
